### ISSUE TITLE
Update Munin

### ISSUE THREAD

**Issue by kroese** [aheimsbakk/container-munin#7]
The container has a pretty old version of Munin, can it be updated to the last release?

**Comment by aheimsbakk** [comment]
Hi, thank you for the interest in this container. I'm currently using the Munin version packaged with the OS, and not looked into installing it from source. Munin version will follow what Alpine provides. At the moment I've not the time to look into installing Munin from source, but would welcome pull request in that direction :)

**Comment by aheimsbakk** [comment]
I've just updated to the latest version of alpine, 3.16. I don't think that affected the version of Munin though...

**Comment by aheimsbakk** [comment]
Try to update your container, and you should get the container based on Alpine 3.16.

**Comment by aheimsbakk** [comment]
I would like to help you start the container. It started as it should in my Kubernetes. How do you invoke the container, the command, Kubernetes or compose definition?
